#ParallelRngManager
language: cpp
os: linux

git:
  depth: 3
  quiet: true

branches:
    only:
        - master

matrix:
  include:
      - env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
          - OPT_ARMADILLO_INT64=On
      - env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
          - OPT_ARMADILLO_INT64=Off
      - env:
          - BUILD_TYPE="Debug"
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
          - OPT_ARMADILLO_INT64=On
      - env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          - OPT_ARMADILLO_INT64=On

      #- addons:
          #apt:
            #sources:
                #- ubuntu-toolchain-r-test
            #packages:
                #- g++-4.9
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      #- addons:
          #apt:
            #sources:
                #- ubuntu-toolchain-r-test
            #packages:
                #- g++-6
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

      #- addons:
          #apt:
            #sources:
                #- ubuntu-toolchain-r-test
            #packages:
                #- g++-7
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

      #- addons:
          #apt:
            #sources:
                #- llvm-toolchain-trusty-5.0
            #packages:
                #- clang-5.0
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

      ##Documentation build
      - env: DOC=On
        script: ./scripts/doc-build.sh


#MATRIX_EVAL allows CC and CXX to be set before dependencies are installed
before_install:
    #- sudo apt-key adv --keyserver packagecloud.io --recv-keys 762E3157
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - eval "${MATRIX_EVAL}"

install:
    - if [ "${DOC}" == "On" ]; then sudo apt-get install -y doxygen doxygen-latex graphviz; fi
    - if [ "${CXX}" == "g++-4.9" ];   then sudo apt-get install -y g++-4.9;   fi
    - if [ "${CXX}" == "g++-5" ];     then sudo apt-get install -y g++-5;     fi
    - if [ "${CXX}" == "g++-6" ];     then sudo apt-get install -y g++-6;     fi
    - if [ "${CXX}" == "g++-7" ];     then sudo apt-get install -y g++-7;     fi
    - if [ "${CXX}" == "clang++-5" ]; then sudo apt-get install -y clang-5.0; fi
    - sudo apt-get install -y libarmadillo-dev libgtest-dev
    - cd /usr/src/gtest && sudo cmake -H. -DCMAKE_INSTALL_PREFIX=/usr && sudo make install

script:
    - ./scripts/travis-build-test.sh

deploy:
    name: Docu-Bot
    provider: pages
    skip-cleanup: true
    github-token: $GH_TRAVISCI_DOCUMENTATION_TOKEN
    keep-history: true
    verbosed: true
    local_dir: doc/html
    on:
        branch: master
        condition: $DOC = On
