#ParallelRngManager
language: cpp
os: linux

git:
  depth: 3
  quiet: true

branches:
    only:
        - master

addons:
  apt:
    packages:
env:
    global:
        - BUILD_TYPE=Release
        - OPT_ARMADILLO_INT64=On

matrix:
  include:
      - before-install:
          - apt-get install -y g++-4.9
        env:
            - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
            - OPT_ARMADILLO_INT64=Off

      #- addons:
          #apt:
            #sources:
                #- ubuntu-toolchain-r-test
            #packages:
                #- g++-4.9
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      #- addons:
          #apt:
            #sources:
                #- ubuntu-toolchain-r-test
            #packages:
                #- g++-6
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

      #- addons:
          #apt:
            #sources:
                #- ubuntu-toolchain-r-test
            #packages:
                #- g++-7
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

      #- addons:
          #apt:
            #sources:
                #- llvm-toolchain-trusty-5.0
            #packages:
                #- clang-5.0
                #- libarmadillo9
                #- libarmadillo-dev
        #env:
            #- MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

      ##Documentation build
      #- addons:
          #apt:
            #packages:
                #- libarmadillo9
                #- libarmadillo-dev
                #- doxygen
                #- doxygen-latex
                #- graphviz
        #env: DOC=On
        #script: ./scripts/doc-build.sh


#MATRIX_EVAL allows CC and CXX to be set before dependencies are installed
before_install:
    #- sudo apt-key adv --keyserver packagecloud.io --recv-keys 762E3157
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install -y libarmadillo-dev
    - eval "${MATRIX_EVAL}"
    - if [ "${CC}" == "gcc-4.9" ]; then sudo apt-get install -y g++-4.9; fi

script:
    - ./scripts/travis-build-test.sh

deploy:
    name: Docu-Bot
    provider: pages
    skip-cleanup: true
    github-token: $GH_TRAVISCI_DOCUMENTATION_TOKEN
    keep-history: true
    verbosed: true
    local_dir: doc/html
    on:
        branch: master
        condition: $DOC = On
