Parallel RNG Manager: parallel_rng::ParallelRngManager< RngT, FloatT > Class Template Reference
parallel_rng::ParallelRngManager< RngT, FloatT > Class Template Reference
#include </home/travis/build/markjolah/ParallelRngManager/include/ParallelRngManager/ParallelRngManager.h>
Public Types
using VecT = arma::Col< FloatT >
using MatT = arma::Mat< FloatT >
using NormalDistT = std::normal_distribution< FloatT >
using UniformDistT = std::uniform_real_distribution< FloatT >
using result_type = typename RngT::result_type
Public Member Functions
ParallelRngManager ()
ParallelRngManager (SeedT seed)
ParallelRngManager (SeedT seed, IdxT max_threads)
void seed (SeedT seed)
void reset ()
void reset (SeedT seed)
void reset (SeedT seed, IdxT max_threads)
SeedT get_init_seed () const
SeedT get_num_threads () const
RngT & generator ()
any_rng::AnyRng< result_type > generic_generator ()
result_type operator() ()
FloatT randu ()
FloatT randn ()
VecT randu (IdxT N)
VecT randn (IdxT N)
MatT randu (IdxT rows, IdxT cols)
MatT randn (IdxT rows, IdxT cols)
template<class Weights = VecT, class IdxT = IdxT>
IdxT resample_dist (const Weights &weights)
template<class Weights = VecT, class IdxT = IdxT>
arma::Col< IdxT > resample_dist (const Weights &weights, IdxT N)
Detailed Description
template<class RngT = DefaultParallelRngT, class FloatT = double>
class parallel_rng::ParallelRngManager< RngT, FloatT >
Definition at line 80 of file ParallelRngManager.h.
Member Typedef Documentation
template<class RngT = DefaultParallelRngT, class FloatT = double> using parallel_rng::ParallelRngManager< RngT, FloatT >::MatT = arma::Mat<FloatT>
Definition at line 84 of file ParallelRngManager.h.
template<class RngT = DefaultParallelRngT, class FloatT = double> using parallel_rng::ParallelRngManager< RngT, FloatT >::NormalDistT = std::normal_distribution<FloatT>
Definition at line 85 of file ParallelRngManager.h.
template<class RngT = DefaultParallelRngT, class FloatT = double> using parallel_rng::ParallelRngManager< RngT, FloatT >::result_type = typename RngT::result_type
Definition at line 87 of file ParallelRngManager.h.
template<class RngT = DefaultParallelRngT, class FloatT = double> using parallel_rng::ParallelRngManager< RngT, FloatT >::UniformDistT = std::uniform_real_distribution<FloatT>
Definition at line 86 of file ParallelRngManager.h.
template<class RngT = DefaultParallelRngT, class FloatT = double> using parallel_rng::ParallelRngManager< RngT, FloatT >::VecT = arma::Col<FloatT>
Definition at line 83 of file ParallelRngManager.h.
Constructor & Destructor Documentation
template<class RngT , class FloatT > parallel_rng::ParallelRngManager< RngT, FloatT >::ParallelRngManager ()
Definition at line 157 of file ParallelRngManager.h.
template<class RngT , class FloatT > parallel_rng::ParallelRngManager< RngT, FloatT >::ParallelRngManager (SeedT seed)
Definition at line 162 of file ParallelRngManager.h.
template<class RngT , class FloatT > parallel_rng::ParallelRngManager< RngT, FloatT >::ParallelRngManager (SeedT seed, IdxT max_threads)
Definition at line 167 of file ParallelRngManager.h.
Member Function Documentation
template<class RngT , class FloatT > RngT & parallel_rng::ParallelRngManager< RngT, FloatT >::generator ()
Definition at line 235 of file ParallelRngManager.h.
Referenced by parallel_rng::ParallelRngManager< RngT, FloatT >::operator()(), and parallel_rng::ParallelRngManager< RngT, FloatT >::resample_dist().
template<class RngT , class FloatT > any_rng::AnyRng< typename ParallelRngManager< RngT, FloatT >::result_type > parallel_rng::ParallelRngManager< RngT, FloatT >::generic_generator ()
Definition at line 243 of file ParallelRngManager.h.
template<class RngT , class FloatT > SeedT parallel_rng::ParallelRngManager< RngT, FloatT >::get_init_seed () const
Definition at line 223 of file ParallelRngManager.h.
template<class RngT , class FloatT > SeedT parallel_rng::ParallelRngManager< RngT, FloatT >::get_num_threads () const
Definition at line 229 of file ParallelRngManager.h.
template<class RngT , class FloatT > ParallelRngManager< RngT, FloatT >::result_type parallel_rng::ParallelRngManager< RngT, FloatT >::operator() ()
Random 64-bit integer
Definition at line 252 of file ParallelRngManager.h.
References parallel_rng::ParallelRngManager< RngT, FloatT >::generator().
template<class RngT , class FloatT > FloatT parallel_rng::ParallelRngManager< RngT, FloatT >::randn () inline
Random standard normal variate
Definition at line 268 of file ParallelRngManager.h.
template<class RngT , class FloatT > ParallelRngManager< RngT, FloatT >::VecT parallel_rng::ParallelRngManager< RngT, FloatT >::randn (IdxT N)
Vector of standard normal variate
Definition at line 290 of file ParallelRngManager.h.
template<class RngT , class FloatT > ParallelRngManager< RngT, FloatT >::MatT parallel_rng::ParallelRngManager< RngT, FloatT >::randn (IdxT rows, IdxT cols)
Matrix of standard normal variate
Definition at line 316 of file ParallelRngManager.h.
template<class RngT , class FloatT > FloatT parallel_rng::ParallelRngManager< RngT, FloatT >::randu ()
Random FloatT uniform on [0,1)
Definition at line 259 of file ParallelRngManager.h.
template<class RngT , class FloatT > ParallelRngManager< RngT, FloatT >::VecT parallel_rng::ParallelRngManager< RngT, FloatT >::randu (IdxT N)
Vector of Random FloatT uniform on [0,1)
Definition at line 277 of file ParallelRngManager.h.
template<class RngT , class FloatT > ParallelRngManager< RngT, FloatT >::MatT parallel_rng::ParallelRngManager< RngT, FloatT >::randu (IdxT rows, IdxT cols)
Matrix of Random FloatT uniform on [0,1)
Definition at line 303 of file ParallelRngManager.h.
template<class RngT , class FloatT > template<class Weights , class IdxT > IdxT parallel_rng::ParallelRngManager< RngT, FloatT >::resample_dist (const Weights & weights)
Definition at line 329 of file ParallelRngManager.h.
References parallel_rng::ParallelRngManager< RngT, FloatT >::generator().
template<class RngT , class FloatT > template<class Weights , class IdxT > arma::Col< IdxT > parallel_rng::ParallelRngManager< RngT, FloatT >::resample_dist (const Weights & weights, IdxT N)
Definition at line 338 of file ParallelRngManager.h.
References parallel_rng::ParallelRngManager< RngT, FloatT >::generator().
template<class RngT , class FloatT > void parallel_rng::ParallelRngManager< RngT, FloatT >::reset ()
Definition at line 196 of file ParallelRngManager.h.
Referenced by parallel_rng::ParallelRngManager< RngT, FloatT >::reset(), and parallel_rng::ParallelRngManager< RngT, FloatT >::seed().
template<class RngT , class FloatT > void parallel_rng::ParallelRngManager< RngT, FloatT >::reset (SeedT seed)
Definition at line 202 of file ParallelRngManager.h.
References parallel_rng::ParallelRngManager< RngT, FloatT >::reset().
template<class RngT , class FloatT > void parallel_rng::ParallelRngManager< RngT, FloatT >::reset (SeedT seed, IdxT max_threads)
Definition at line 208 of file ParallelRngManager.h.
template<class RngT , class FloatT > void parallel_rng::ParallelRngManager< RngT, FloatT >::seed (SeedT seed)
Definition at line 186 of file ParallelRngManager.h.
References parallel_rng::ParallelRngManager< RngT, FloatT >::reset().
The documentation for this class was generated from the following file:
ParallelRngManager.h